"""Custom

Revision ID: a9a397d10e8f
Revises: 40719081ddf9
Create Date: 2022-07-22 01:41:34.401337

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a9a397d10e8f'
down_revision = '40719081ddf9'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'login_history', ['id'])
    op.create_unique_constraint(None, 'roles', ['id'])
    op.create_unique_constraint(None, 'social_accounts', ['id'])
    op.add_column('users', sa.Column('date_of_birth', sa.Date(), nullable=False))
    op.create_unique_constraint(None, 'users', ['id', 'email', 'date_of_birth'])
    op.create_unique_constraint(None, 'users', ['id'])
    op.create_unique_constraint(None, 'users_roles', ['id'])

    op.execute( """
        CREATE TABLE IF NOT EXISTS "users_birthdays_1920_to_1979"
        PARTITION OF "users"
        FOR VALUES FROM ('1920-01-01') TO ('1979-12-31');
        """)

    op.execute( """
        CREATE TABLE IF NOT EXISTS "users_birthdays_1980_to_2003"
        PARTITION OF "users"
        FOR VALUES FROM ('1980-01-01') TO ('2003-12-31');
        """)

    op.execute("""
        CREATE TABLE IF NOT EXISTS "users_birthdays_2004_to_2022"
        PARTITION OF "users"
        FOR VALUES FROM ('2004-01-01') TO ('2022-12-31');
        """)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users_roles', type_='unique')
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_column('users', 'date_of_birth')
    op.drop_constraint(None, 'social_accounts', type_='unique')
    op.drop_constraint(None, 'roles', type_='unique')
    op.drop_constraint(None, 'login_history', type_='unique')
    # ### end Alembic commands ###
